(function () {
  "use strict";
  const data = window.WASLA_GUIDE;
  const actor = code => data.actors[code];
  const esc = value => String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const badges = codes => codes.map(code => `<span class="actor ${actor(code).color}">${actor(code).icon} ${actor(code).label}</span>`).join("");
  let journeyIndex = 0, journeyPhase = "all", activeRole = "admin", messageFilter = "all", moneyMode = "cod", exceptionFilter = "all", sampleIndex = -1;

  document.querySelector("#core-flow").innerHTML = data.coreFlow.map((item, index) => `<div class="core-node"><span>${item[0]}</span><b>${item[1]}</b><small>${item[2]}</small></div>${index < data.coreFlow.length - 1 ? '<i aria-hidden="true">→</i>' : ''}`).join("");

  document.querySelector("#phase-filter").innerHTML = data.phases.map(item => `<button data-phase="${item.id}" class="${item.id === "all" ? "active" : ""}">${item.label}</button>`).join("");
  function visibleJourney() { return journeyPhase === "all" ? data.journey : data.journey.filter(item => item.phase === journeyPhase); }
  function renderJourney() {
    const list = visibleJourney();
    journeyIndex = Math.min(journeyIndex, list.length - 1);
    document.querySelector("#journey-list").innerHTML = list.map((item, index) => `<li class="journey-step ${index < journeyIndex ? "done" : index === journeyIndex ? "current" : "future"}"><button data-journey="${index}" aria-current="${index === journeyIndex ? "step" : "false"}"><span class="step-marker">${index < journeyIndex ? "✓" : index + 1}</span><span class="step-copy"><small>${esc(item.kicker)}</small><b>${esc(item.title)}</b>${item.status ? `<span lang="ar" dir="rtl">${esc(item.statusAr)}</span><code>${esc(item.status)}</code>` : `<span class="preorder">${esc(item.statusAr)}</span>`}</span><span class="waiting">Waiting: ${esc(item.waiting)}</span></button></li>`).join("");
    document.querySelectorAll("[data-journey]").forEach(button => button.onclick = () => { journeyIndex = Number(button.dataset.journey); renderJourney(); });
    const item = list[journeyIndex];
    const linked = (item.messages || []).map(id => `<button class="inline-link" data-open-message="${id}">${id}</button>`).join("");
    document.querySelector("#journey-detail").innerHTML = `<div class="detail-top"><span class="stage-icon">${item.icon}</span><span>${badges(item.actors)}</span></div><p class="eyebrow">${esc(item.kicker)}</p><h3>${esc(item.title)}</h3>${item.status ? `<div class="customer-status"><small>Customer sees</small><b lang="ar" dir="rtl">${esc(item.statusAr)}</b><code>${esc(item.status)}</code></div>` : ""}<div class="detail-block"><h4>What is happening?</h4><p>${esc(item.summary)}</p></div><div class="detail-block admin-action"><h4>🧑‍💼 Admin action</h4><p>${esc(item.admin)}</p></div><div class="detail-block"><h4>What moves it forward?</h4><p>${esc(item.next)}</p></div>${linked ? `<div class="detail-block"><h4>Relevant messages</h4><div>${linked}</div></div>` : ""}<details class="source"><summary>Source trace</summary><p>${esc(item.source)}</p></details>`;
    document.querySelectorAll("[data-open-message]").forEach(button => button.onclick = () => openMessage(button.dataset.openMessage));
    document.querySelector("#journey-position").textContent = `${journeyIndex + 1} / ${list.length}`;
    document.querySelector("#journey-prev").disabled = journeyIndex === 0;
    document.querySelector("#journey-next").disabled = journeyIndex === list.length - 1;
  }
  document.querySelectorAll("[data-phase]").forEach(button => button.onclick = () => { journeyPhase = button.dataset.phase; journeyIndex = 0; document.querySelectorAll("[data-phase]").forEach(x => x.classList.toggle("active", x === button)); renderJourney(); });
  document.querySelector("#journey-prev").onclick = () => { journeyIndex--; renderJourney(); };
  document.querySelector("#journey-next").onclick = () => { journeyIndex++; renderJourney(); };

  document.querySelector("#role-tabs").innerHTML = Object.keys(data.roles).map(code => `<button role="tab" data-role="${code}" aria-selected="${code === activeRole}">${actor(code).icon} ${actor(code).label}</button>`).join("");
  function renderRole() { const role = data.roles[activeRole]; document.querySelector("#role-detail").innerHTML = `<div class="role-intro ${actor(activeRole).color}"><span>${actor(activeRole).icon}</span><div><p class="eyebrow">${actor(activeRole).label.toUpperCase()} VIEW</p><h3>${esc(role.summary)}</h3></div></div><ol class="role-actions">${role.actions.map((item,index) => `<li><span>${index+1}</span>${esc(item)}</li>`).join("")}</ol>`; document.querySelectorAll("[data-role]").forEach(button => button.setAttribute("aria-selected", button.dataset.role === activeRole)); }
  document.querySelectorAll("[data-role]").forEach(button => button.onclick = () => { activeRole = button.dataset.role; renderRole(); });

  document.querySelector("#status-map").innerHTML = data.states.map(state => `<details class="status-card"><summary><span class="status-dot"></span><div><b lang="ar" dir="rtl">${esc(state.ar)}</b><code>${esc(state.code)}</code></div><span class="plus">+</span></summary><div class="status-body"><p>${esc(state.meaning)}</p><dl><div><dt>Enters when</dt><dd>${esc(state.enter)}</dd></div><div><dt>Who has the ball?</dt><dd>${badges(state.owner)}</dd></div><div><dt>Possible next states</dt><dd>${state.next.length ? state.next.map(x=>`<code>${esc(x)}</code>`).join(" ") : "Final state"}</dd></div></dl><small>Source: 03_Order State Machine §§3–9; Arabic projection: 07_Customer Website §29</small></div></details>`).join("");

  document.querySelector("#message-filters").innerHTML = [["all","All"],["customer","Customer"],["store","Store"]].map(x=>`<button data-message-filter="${x[0]}" class="${x[0] === "all" ? "active" : ""}">${x[1]}</button>`).join("");
  function renderMessages() { const list = messageFilter === "all" ? data.messages : data.messages.filter(x=>x.audience === messageFilter); document.querySelector("#message-list").innerHTML = list.map(item => `<details class="message-card" id="message-${item.id}"><summary><div><span class="message-id">${item.id}</span><b>${esc(item.purpose)}</b><small>${esc(item.when)}</small></div><span class="plus">+</span></summary><div class="message-body"><div class="message-meta"><b>When used</b><p>${esc(item.when)}</p></div><pre lang="ar" dir="rtl">${esc(item.text)}</pre><div class="message-footer"><small>Source: ${esc(item.source)}</small><button data-copy-message="${item.id}">Copy Arabic message</button></div></div></details>`).join(""); document.querySelectorAll("[data-copy-message]").forEach(button => button.onclick = event => { event.preventDefault(); copyMessage(button.dataset.copyMessage); }); }
  function copyMessage(id) { const item=data.messages.find(x=>x.id===id); navigator.clipboard?.writeText(item.text).then(()=>toast("Arabic message copied")).catch(()=>fallbackCopy(item.text)); }
  function fallbackCopy(text) { const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();toast("Arabic message copied"); }
  function openMessage(id) { messageFilter="all";renderMessages();location.hash="messages";setTimeout(()=>{const card=document.querySelector(`#message-${CSS.escape(id)}`);if(card){card.open=true;card.scrollIntoView({behavior:"smooth",block:"center"});}},100); }
  document.querySelectorAll("[data-message-filter]").forEach(button => button.onclick = () => { messageFilter=button.dataset.messageFilter;document.querySelectorAll("[data-message-filter]").forEach(x=>x.classList.toggle("active",x===button));renderMessages(); });

  document.querySelector("#pricing-cards").innerHTML = data.pricing.map(item => `<article><strong>${item[0]}</strong><b>${item[1]}</b><p>${item[2]}</p></article>`).join("");
  function round50HalfUp(value) { return Math.floor((value + 25) / 50) * 50; }
  function renderCalc() { const merchant=Math.max(0,Math.round(Number(document.querySelector("#merchant-price").value)||0)), qty=Math.max(1,Math.round(Number(document.querySelector("#quantity").value)||1)), unrounded=merchant*110/100, unit=round50HalfUp(unrounded), line=unit*qty, total=line+1500; document.querySelector("#calculation-result").innerHTML = `<div><span>Merchant unit</span><b>${merchant.toLocaleString("en-US")} YAR</b></div><i>× 1.10</i><div><span>Unrounded</span><b>${unrounded.toLocaleString("en-US")} YAR</b></div><i>nearest 50</i><div class="highlight"><span>Customer unit</span><b>${unit.toLocaleString("en-US")} YAR</b></div><div><span>Line (${qty} units)</span><b>${line.toLocaleString("en-US")} YAR</b></div><i>+ 1,500 delivery</i><div class="highlight"><span>Customer total</span><b>${total.toLocaleString("en-US")} YAR</b></div>`; }
  document.querySelector("#merchant-price").oninput=renderCalc;document.querySelector("#quantity").oninput=renderCalc;
  document.querySelector("#money-tabs").innerHTML = Object.entries(data.moneyFlows).map(([id,item])=>`<button data-money="${id}" class="${id===moneyMode?"active":""}">${item.label}</button>`).join("");
  function renderMoney(){const flow=data.moneyFlows[moneyMode];document.querySelector("#money-flow").innerHTML=flow.steps.map((step,index)=>`<div><span>${index+1}</span><p>${esc(step)}</p></div>${index<flow.steps.length-1?'<i>→</i>':''}`).join("");document.querySelectorAll("[data-money]").forEach(x=>x.classList.toggle("active",x.dataset.money===moneyMode));}
  document.querySelectorAll("[data-money]").forEach(button=>button.onclick=()=>{moneyMode=button.dataset.money;renderMoney();});

  document.querySelector("#timer-list").innerHTML=data.timers.map(item=>`<article class="timer-card"><div><span class="timer-icon">◷</span><div><h3>${esc(item.title)}</h3><p>Starts: <b>${esc(item.start)}</b></p></div></div><ol>${item.marks.map(mark=>`<li>${esc(mark)}</li>`).join("")}</ol><p class="timer-note">🧑‍💼 ${esc(item.note)}</p></article>`).join("");
  const exceptionAreas=[["all","All"],["confirmation","Confirmation"],["store","Store"],["payment","Payment"],["authorization","Authorization"],["delivery","Delivery"],["cash","Cash"]];
  document.querySelector("#exception-filters").innerHTML=exceptionAreas.map(x=>`<button data-exception="${x[0]}" class="${x[0]==="all"?"active":""}">${x[1]}</button>`).join("");
  function renderExceptions(){const list=exceptionFilter==="all"?data.exceptions:data.exceptions.filter(x=>x.area===exceptionFilter);document.querySelector("#exception-list").innerHTML=list.map(item=>`<details class="exception-card"><summary><span>!</span><b>${esc(item.title)}</b><code>${esc(item.result)}</code><i class="plus">+</i></summary><div><h4>What happened?</h4><p>${esc(item.what)}</p><h4>Admin handles it</h4><p>${esc(item.admin)}</p><h4>Order result</h4><code>${esc(item.result)}</code></div></details>`).join("");}
  document.querySelectorAll("[data-exception]").forEach(button=>button.onclick=()=>{exceptionFilter=button.dataset.exception;document.querySelectorAll("[data-exception]").forEach(x=>x.classList.toggle("active",x===button));renderExceptions();});

  function renderSample(){document.querySelector("#sample-progress").innerHTML=data.sample.map((item,index)=>`<button data-sample="${index}" class="${index<sampleIndex?"done":index===sampleIndex?"current":""}" aria-label="${esc(item.title)}"><span>${index<sampleIndex?"✓":index+1}</span></button>`).join("");const item=sampleIndex<0?null:data.sample[sampleIndex];document.querySelector("#sample-card").innerHTML=item?`<p class="eyebrow">STEP ${sampleIndex+1} OF ${data.sample.length}</p><h3>${esc(item.title)}</h3><div class="sample-status" lang="ar" dir="rtl">${esc(item.status)}</div><p><b>Who has the ball?</b> ${esc(item.owner)}</p><p>${esc(item.text)}</p><div class="admin-action"><h4>🧑‍💼 Admin action</h4><p>${esc(item.admin)}</p></div>${item.message?`<button class="inline-link" data-sample-message="${item.message}">View ${item.message}</button>`:""}`:`<div class="sample-empty"><span>▣</span><h3>Ready to follow one order?</h3><p>Walk through a successful COD order using the approved Wasla rules.</p></div>`;document.querySelector("#sample-next").textContent=sampleIndex<0?"Start order →":sampleIndex===data.sample.length-1?"Finished ✓":"Next event →";document.querySelector("#sample-next").disabled=sampleIndex===data.sample.length-1;document.querySelectorAll("[data-sample]").forEach(button=>button.onclick=()=>{sampleIndex=Number(button.dataset.sample);renderSample();});document.querySelector("[data-sample-message]")?.addEventListener("click",e=>openMessage(e.currentTarget.dataset.sampleMessage));}
  document.querySelector("#sample-next").onclick=()=>{sampleIndex++;renderSample();};document.querySelector("#sample-reset").onclick=()=>{sampleIndex=-1;renderSample();};

  document.querySelector("#perspective-grid").innerHTML=data.perspectives.map(item=>`<article><span>${item.icon}</span><h3>${item.title}</h3><ol>${item.steps.map(step=>`<li>${esc(step)}</li>`).join("")}</ol></article>`).join("");
  document.querySelector("#dashboard-grid").innerHTML=data.dashboard.map(item=>`<article><span>✓</span><div><h3>${item[0]}</h3><p>${item[1]}</p></div></article>`).join("");
  document.querySelector("#rules-grid").innerHTML=data.rules.map((rule,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><p>${esc(rule)}</p></article>`).join("");
  document.querySelector("#review-list").innerHTML=data.review.map(item=>`<details><summary><b>${esc(item.title)}</b><span class="review-badge">Open / explicit boundary</span></summary><p>${esc(item.text)}</p><small>Source: ${esc(item.source)}</small></details>`).join("");

  const dialog=document.querySelector("#sources-dialog");document.querySelector("#source-list").innerHTML=data.sources.map(item=>`<div><b>${item[0]}</b><code>${item[1]}</code></div>`).join("");document.querySelector("#sources-button").onclick=()=>dialog.showModal();document.querySelectorAll("[data-close-dialog]").forEach(button=>button.onclick=()=>dialog.close());dialog.onclick=e=>{if(e.target===dialog)dialog.close();};
  const menu=document.querySelector("#menu-button"),nav=document.querySelector("#site-nav");menu.onclick=()=>{const open=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!open));nav.classList.toggle("open",!open);};nav.querySelectorAll("a").forEach(link=>link.onclick=()=>{menu.setAttribute("aria-expanded","false");nav.classList.remove("open");});
  function toast(text){const node=document.querySelector("#toast");node.textContent=text;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),1800);}
  renderJourney();renderRole();renderMessages();renderCalc();renderMoney();renderExceptions();renderSample();
})();
